name: Integration Build
run-name: "1.3.${{ github.run_number }} • ${{ github.event.pull_request.title != '' && github.event.pull_request.title || github.head_ref || github.ref_name }}"
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:
env:
  MAJOR_VERSION: 1
  MINOR_VERSION: 3

jobs:
  build-linux:
    name: Integration Build
    uses: ./.github/workflows/build-linux.yml
    with:
      major_version: '1'
      minor_version: '3'
      run_number: ${{ github.run_number }}
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}

  docker-build-image-for-churchbulletin-ui:
    name: Publish Release Candidate
    needs: [build-linux]
    if: success()
    uses: ./.github/workflows/docker-build-push.yml
    with:
      major_version: '1'
      minor_version: '3'
      run_number: ${{ github.run_number }}
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

  deploy-to-tdd:
    name: TDD
    needs: [docker-build-image-for-churchbulletin-ui]
    if: success()
    uses: ./.github/workflows/deploy-tdd.yml
    with:
      major_version: '1'
      minor_version: '3'
      run_number: ${{ github.run_number }}
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      octo_api_key: ${{ secrets.OCTO_API_KEY }}
      octopus_url: ${{ secrets.OCTOPUS_URL }}
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

  deploy-to-uat:
    name: UAT
    needs: [deploy-to-tdd]
    if: success()
    uses: ./.github/workflows/deploy-uat.yml
    with:
      major_version: '1'
      minor_version: '3'
      run_number: ${{ github.run_number }}
    secrets:
      octo_api_key: ${{ secrets.OCTO_API_KEY }}
      octopus_url: ${{ secrets.OCTOPUS_URL }}

  deploy-to-prod:
    name: Prod
    needs: [deploy-to-uat]
    if: success()
    uses: ./.github/workflows/deploy-prod.yml
    with:
      major_version: '1'
      minor_version: '3'
      run_number: ${{ github.run_number }}
    secrets:
      octo_api_key: ${{ secrets.OCTO_API_KEY }}
      octopus_url: ${{ secrets.OCTOPUS_URL }}          
